const fs = require("fs"), path = require("path");
const dir = path.join(__dirname, "examples");
// Display name -> file, in menu order. These are AUTHENTIC saved bird arrays
// from the original "Saved Runs" folder (CR line endings converted to LF).
const order = [
  ["Two species (2/22/99)",   "two-species.txt"],
  ["Two species 3 (2/25/99)", "two-species-3.txt"],
  ["Nice run",                "nice-run.txt"],
  ["First run",               "first-run.txt"],
  ["Long run (2/1/99)",       "long-run.txt"],
];
let out = "// Auto-generated by gen_data.js -- example saved bird arrays embedded\n";
out += "// so the app runs offline straight from file:// with no server.\n";
out += "// Format: line 1 = year, then 'length:width:curve:sex:age:life' per bird.\n";
out += "window.SSS_RUNS = [\n";
for (const [name, file] of order) {
  const txt = fs.readFileSync(path.join(dir, file), "utf8").replace(/\s+$/, "");
  out += "  { name: " + JSON.stringify(name) + ", text: " + JSON.stringify(txt) + " },\n";
}
out += "];\n";
fs.writeFileSync(path.join(__dirname, "birds-data.js"), out);
console.log("wrote birds-data.js with", order.length, "runs");
