const fs = require("fs"), path = require("path");
const dir = path.join(__dirname, "examples");
// Scenario presets, in menu order. These set up fresh runs that reproduce the
// experiments from the original project (intact vs. fragmented habitat, random
// mortality events, and the two together).
const order = [
  "intact.json",
  "frag30.json",
  "frag60.json",
  "random-events.json",
  "frag-plus-events.json",
];
let out = "// Auto-generated by gen_data.js -- scenario presets embedded so the\n";
out += "// app runs offline straight from file:// with no server.\n";
out += "window.FRAG_SCENARIOS = [\n";
for (const file of order) {
  const obj = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8"));
  out += "  " + JSON.stringify(obj) + ",\n";
}
out += "];\n";
fs.writeFileSync(path.join(__dirname, "scenarios-data.js"), out);
console.log("wrote scenarios-data.js with", order.length, "scenarios");
