// Auto-generated by gen_data.js -- scenario presets embedded so the
// app runs offline straight from file:// with no server.
window.FRAG_SCENARIOS = [
  {"name":"Intact habitat (10×10)","size":10,"frag":0,"settings":{"mp":0.01,"br":2,"rhalf":false,"fluc":false},"note":"A continuous habitat. Population fills the grid to carrying capacity."},
  {"name":"30% fragmentation","size":12,"frag":30,"applyFrag":true,"settings":{"mp":0.01,"br":2,"make_mode":2,"rhalf":false,"fluc":false},"note":"30% of cells walled off (solid). Walls block dispersal and hurt neighbours."},
  {"name":"60% fragmentation","size":12,"frag":60,"applyFrag":true,"settings":{"mp":0.01,"br":2,"make_mode":2,"rhalf":false,"fluc":false},"note":"Heavy fragmentation. The population often collapses toward extinction."},
  {"name":"Random mortality events","size":12,"frag":0,"settings":{"mp":0.05,"br":2,"rhalf":true,"prob":50,"fluc":false},"note":"Frequent local catastrophes wipe out cells at random; dispersal helps recolonise."},
  {"name":"Fragmentation + random events","size":12,"frag":30,"applyFrag":true,"settings":{"mp":0.05,"br":2,"make_mode":2,"rhalf":true,"prob":100,"fluc":false},"note":"Both stressors at once — the regime where an optimal dispersal rate appears."},
];
