const fs = require("fs"), path = require("path");
const dir = path.join(__dirname, "examples");
// Display name -> file, in menu order. These are the AUTHENTIC creatures from
// the original "Examples" folder. Order: headline movers first, then the other
// evolved creatures, then the hand-built physics tests.
const order = [
  ["gallop [evolved]",       "gallop-evolved.txt"],
  ["Runner [evolved]",       "runner-evolved.txt"],
  ["Two leg walker [evolved]","two-leg-walker-evolved.txt"],
  ["Slow Walker [evolved]",  "slow-walker-evolved.txt"],
  ["Simple tri-leg [evolved]","simple-tri-leg-evolved.txt"],
  ["Wheel [evolved]",        "wheel-evolved.txt"],
  ["Slider [evolved]",       "slider-evolved.txt"],
  ["Complex slider [evolved]","complex-slider-evolved.txt"],
  ["Complex Worm [evolved]", "complex-worm-evolved.txt"],
  ["Step Example 1 [evolved]","step-example-1-evolved.txt"],
  ["Step Example 2 [evolved]","step-example-2-evolved.txt"],
  ["Messed Up [evolved]",    "messed-up-evolved.txt"],
  ["Box",                    "box.txt"],
  ["Two Triangle",           "two-triangle.txt"],
  ["Weighted Box",           "weighted-box.txt"],
  ["Vert Falling Spring",    "vert-falling-spring.txt"],
  ["Horz Falling Spring",    "horz-falling-spring.txt"],
  ["Throw",                  "throw.txt"],
  ["Test",                   "test.txt"],
];
let out = "// Auto-generated by gen_data.js -- example creatures embedded so the\n";
out += "// app runs offline straight from file:// with no server.\n";
out += "window.CREATURE_DATA = [\n";
for (const [name, file] of order) {
  const txt = fs.readFileSync(path.join(dir, file), "utf8").replace(/\s+$/,"");
  out += "  { name: " + JSON.stringify(name) + ", text: " + JSON.stringify(txt) + " },\n";
}
out += "];\n";
fs.writeFileSync(path.join(__dirname, "creatures-data.js"), out);
console.log("wrote creatures-data.js with", order.length, "creatures");
